#!/usr/bin/env python3
"""Ajanlara HIC gitmeyecek metinler: kendiliginden degismezler + onayli ceviriler.

DEGISMEZ: klavye tus adlari (W A S D Q E ...), diyagram numaralari, birimler.
Bunlar cevrilirse oyun yanlis bilgi verir — "W" tusuna "I" yazamayiz. Ajana
sormaya gerek yok, mekanik olarak ayiriyoruz.

SABIT: pilot sayfasinda oyunda dogrulanmis ceviriler. Yeniden cevirtmek yerine
aynen kullaniyoruz ki dogrulanmis sonuc geri gitmesin.
"""
import re

# Harf icermeyen (saf sayi/simge) ya da 1-2 karakterlik metinler degismez.
# 'P\n', 'W\n' gibi sondaki newline'lar korunur — kutu hizalamasi ona bagli.
HARFSIZ = re.compile(r"^[^A-Za-z]*$")


def degismez_mi(metin):
    s = metin.strip()
    if not s:
        return True
    if HARFSIZ.match(metin):
        return True          # "0\n1\n2\n3", "32", "16"
    if len(s) <= 2:
        return True          # "W", "A", "S", "D", "F", "B"
    return False


# Pilotta oyunda dogrulanan ceviriler (ekran goruntusuyle onaylandi)
SABIT = {
    "Lift": "Taşıma Kuvveti",
    "Airflow": "Hava Akışı",
    "Getting a Lift Up": "Yukarı Doğru Taşınmak",
    "Small Delta Wing\nRWA = 0.5": "Küçük Delta Kanat\nRWA = 0,5",
    "Delta Wing\nRWA = 2.0": "Delta Kanat\nRWA = 2,0",

    "With a plane, the lift is generated by air being \n"
    "shaped by the wings. Air deflected downwards \n"
    "adds force upwards.\n\n"
    "Basic rules of thumb are:\n"
    " 1. Larger wings generate more lift.\n"
    " 2. Faster airflow generates more lift.\n"
    " 3. If the angle of attack is too great the wing stalls \n"
    "     and produces next to no lift, only drag.":
        "Bir uçakta taşıma kuvveti, havanın kanatlar\n"
        "tarafından yönlendirilmesiyle oluşur. Aşağı\n"
        "yönlendirilen hava yukarı doğru kuvvet üretir.\n\n"
        "Temel kurallar şunlardır:\n"
        " 1. Daha büyük kanatlar daha çok taşıma üretir.\n"
        " 2. Daha hızlı hava akışı daha çok taşıma üretir.\n"
        " 3. Hücum açısı çok büyükse kanat tutunmasını \n"
        "     kaybeder ve taşıma değil sadece sürüklenme üretir.",

    "The part details in the Construction \n"
    "Interface show the \"Relative Wing \n"
    "Area\" of each part, which makes it\n"
    "easy for you to compare them.":
        "Yapım Arayüzü'ndeki parça ayrıntıları\n"
        "her parçanın \"Bağıl Kanat Alanı\"nı\n"
        "gösterir; bu da parçaları\n"
        "karşılaştırmayı kolaylaştırır.",

    "With a plane, lift is generated by air being shaped as it passes around the wings. Wings in KSP are \n"
    "symmetrical, if there is no angle of attack (angle into the airstream), there is no lift generated by wings.":
        "Bir uçakta taşıma kuvveti, hava kanatların çevresinden geçerken şekillendirilmesiyle oluşur. KSP'deki \n"
        "kanatlar simetriktir; hücum açısı (hava akımına giriş açısı) yoksa kanatlar taşıma kuvveti üretmez.",
}


if __name__ == "__main__":
    testler = [("W\n", True), ("WASD", False), ("0\n1\n2", True),
               ("Lift", False), ("32", True), ("F", True),
               ("RWA = 2.0", False), ("  ", True)]
    for m, bekle in testler:
        s = degismez_mi(m)
        gosterim = m.replace("\n", "\\n")
        durum = "degismez" if s else "cevrilecek"
        print(f"  {'OK ' if s == bekle else 'YANLIS'} {gosterim!r:12} -> {durum}")
    print(f"\n  sabit ceviri: {len(SABIT)}")
